# Generated by Django 4.1.10 on 2023-09-21 02:39

import cfehome.storages.backends
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_stripe_price_id_product_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattachment",
            name="file",
            field=models.FileField(
                storage=cfehome.storages.backends.ProtectedFileStorage(),
                upload_to=products.models.handle_product_attachment_upload,
            ),
        ),
    ]
